---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: awx-archlinux
    image: archlinux/base
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        awx_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: archlinux
verifier:
  name: goss
  lint:
    name: yamllint
