---
# tasks file for awx
- name: check system requirements
  assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_processor_vcpus >= 2
    msg: >
      Your system does not minimum system requirements, based on
      https://github.com/ansible/awx/blob/devel/INSTALL.md#system-requirements

- name: unarchive software
  unarchive:
    src: "https://github.com/ansible/awx/archive/{{ awx_version }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/awx-{{ awx_version }}"
  notify:
    - run awx installer

- name: configure inventory
  template:
    src: inventory.j2
    dest: "/tmp/awx-{{ awx_version }}/installer/inventory"

- name: install requirements
  pip:
    name: "{{ awx_pip_requirements }}"
    state: "{{ awx_package_state }}"

- name: install requirements on localhost
  pip:
    name: ansible-tower-cli
    state: "{{ awx_package_state }}"
  connection: local

- name: flush handlers
  meta: flush_handlers

- name: configure organizations
  include: organization.yml
  with_items: "{{ awx_organizations }}"
  loop_control:
    loop_var: organization
  when:
    - awx_organizations is defined
