---
- name: create organization
  tower_organization:
    name: "{{ organization.name }}"
    description: "{{ organization.description | default(organization.name) }}"
    tower_host: "http://{{ ansible_default_ipv4.address }}"
    tower_username: admin
    tower_password: "{{ awx_admin_password }}"
    tower_verify_ssl: "{{ awx_tower_verify_ssl }}"
  register: createorganization
  until: createorganization is succeeded
  retries: 3
  delegate_to: localhost

- name: create users in organization
  include_tasks: user.yml
  with_items: "{{ organization.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  when:
    - organization.users is defined

- name: create teams in organization
  include_tasks: team.yml
  with_items: "{{ organization.teams }}"
  loop_control:
    loop_var: team
    label: "{{ team.name }}"
  when:
    - organization.teams is defined

- name: create credentials in organization
  include_tasks: credential.yml
  with_items: "{{ organization.credentials }}"
  loop_control:
    loop_var: credential
    label: "{{ credential.name }}"
  when:
    - organization.credentials is defined

- name: create projects in organization
  include_tasks: project.yml
  with_items: "{{ organization.projects }}"
  loop_control:
    loop_var: project
    label: "{{ project.name }}"
  when:
    - organization.projects is defined

- name: create inventory in organization
  include_tasks: inventory.yml
  with_items: "{{ organization.inventories }}"
  loop_control:
    loop_var: inventory
    label: "{{ inventory.name }}"
  when:
    - organization.inventories is defined

- name: create job_templates in organization
  include_tasks: job_template.yml
  with_items: "{{ organization.job_templates }}"
  loop_control:
    loop_var: job_template
    label: "{{ job_template.name }}"
  when:
    - organization.job_templates is defined
  register: createjobtemplateinorganization
  until: createjobtemplateinorganization is succeeded
  retries: 3
