---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  vars:
    python_pip_modules:
      - name: ansible

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.python_pip
    - ansible-role-awx
