---
# handlers file for awx
- name: run installer
  command: ansible-playbook -i inventory install.yml
  args:
    chdir: /tmp/awx-{{ awx_version }}/installer
  notify:
    - wait for awx

- name: wait for awx
  uri:
    url: "http://{{ ansible_default_ipv4.address }}/#/login"
  register: result
  until: result.status == 200
  retries: 10
  delay: 30
